const createRegisteredUser = ({
  id,
  name,
  email,
  password,
  role,
  status,
  createdAt,
  avatar = null,
  phone,
  studentId = null,
  course = null,
  campus = null,
  yearLevel = null,
  department = null,
  position = null,
  dateOfBirth,
  address,
  bio,
  emergencyContact,
  interests,
  preferences,
  lastLoginAt,
}) => ({
  id,
  name,
  firstName: name.split(' ')[0],
  lastName: name.split(' ').slice(1).join(' '),
  email,
  password,
  role,
  status,
  createdAt,
  updatedAt: createdAt,
  lastLoginAt,
  avatar,
  phone,
  studentId,
  course,
  campus,
  yearLevel,
  department,
  position,
  dateOfBirth,
  address,
  bio,
  emergencyContact,
  interests,
  preferences,
});

const registeredUsers = [
  createRegisteredUser({
    id: 'user-demo',
    name: 'Demo User',
    email: 'user@demo.com',
    password: 'Demo@123',
    role: 'user',
    status: 'active',
    createdAt: '2026-03-01T09:00:00.000Z',
    lastLoginAt: '2026-05-02T06:30:00.000Z',
    phone: '+61 412 000 001',
    studentId: 'KOI2026001',
    course: 'Bachelor of Information Technology',
    campus: 'Sydney',
    yearLevel: 'Year 1',
    dateOfBirth: '2004-04-18',
    address: 'Level 2, 123 Kent Street, Sydney NSW 2000',
    bio: 'New student exploring campus activities and technology meetups.',
    emergencyContact: {
      name: 'Jordan User',
      relationship: 'Brother',
      phone: '+61 412 000 099',
    },
    interests: ['AI', 'Networking', 'Workshops'],
    preferences: {
      notifications: true,
      emailDigest: false,
      preferredEventCategories: ['Technology', 'Career'],
    },
  }),
  createRegisteredUser({
    id: 'organizer-demo',
    name: 'Demo Organizer',
    email: 'organizer@demo.com',
    password: 'Demo@123',
    role: 'organizer',
    status: 'active',
    createdAt: '2026-02-24T10:30:00.000Z',
    lastLoginAt: '2026-05-03T03:15:00.000Z',
    phone: '+61 412 000 002',
    department: 'Student Engagement',
    position: 'Events Coordinator',
    campus: 'Sydney',
    dateOfBirth: '1994-08-11',
    address: 'KOI Sydney Campus, 31 Market Street, Sydney NSW 2000',
    bio: 'Coordinates student workshops, orientation events, and networking sessions.',
    emergencyContact: {
      name: 'Nina Organizer',
      relationship: 'Partner',
      phone: '+61 412 000 098',
    },
    interests: ['Student Experience', 'Event Planning', 'Community Building'],
    preferences: {
      notifications: true,
      emailDigest: true,
      preferredEventCategories: ['Academic', 'Networking', 'Careers'],
    },
  }),
  createRegisteredUser({
    id: 'admin-demo',
    name: 'Demo Admin',
    email: 'admin@demo.com',
    password: 'Demo@123',
    role: 'admin',
    status: 'active',
    createdAt: '2026-02-20T08:15:00.000Z',
    lastLoginAt: '2026-05-04T00:40:00.000Z',
    phone: '+61 412 000 003',
    department: 'Platform Operations',
    position: 'System Administrator',
    campus: 'Sydney',
    dateOfBirth: '1990-01-23',
    address: 'KOI Head Office, Sydney NSW 2000',
    bio: 'Maintains platform operations, user access, and administrative workflows.',
    emergencyContact: {
      name: 'Alex Admin',
      relationship: 'Sibling',
      phone: '+61 412 000 097',
    },
    interests: ['Security', 'Operations', 'Analytics'],
    preferences: {
      notifications: true,
      emailDigest: true,
      preferredEventCategories: ['Operations', 'Leadership'],
    },
  }),
  createRegisteredUser({
    id: 'master-admin',
    name: 'Sachin Thapa',
    email: 'sachin@demo.com',
    password: 'Demo@123',
    role: 'admin',
    status: 'active',
    createdAt: '2026-02-20T08:15:00.000Z',
    lastLoginAt: '2026-05-04T02:05:00.000Z',
    phone: '+61 412 000 004',
    department: 'Platform Operations',
    position: 'Lead Administrator',
    campus: 'Sydney',
    dateOfBirth: '1993-07-14',
    address: 'KOI Head Office, Sydney NSW 2000',
    bio: 'Oversees administration, operations, and product configuration for Smart Events.',
    emergencyContact: {
      name: 'Mina Thapa',
      relationship: 'Spouse',
      phone: '+61 412 000 096',
    },
    interests: ['Product Management', 'Automation', 'Reporting'],
    preferences: {
      notifications: true,
      emailDigest: true,
      preferredEventCategories: ['Technology', 'Leadership', 'Operations'],
    },
  }),
  createRegisteredUser({
    id: 'user-sarah-johnson',
    name: 'Sarah Johnson',
    email: 'sarah.johnson@student.koi.edu.au',
    password: 'Demo@123',
    role: 'user',
    status: 'active',
    createdAt: '2026-03-05T09:20:00.000Z',
    lastLoginAt: '2026-05-01T05:22:00.000Z',
    phone: '+61 401 234 111',
    studentId: 'KOI2024002',
    course: 'Bachelor of Business',
    campus: 'Sydney',
    yearLevel: 'Year 2',
    dateOfBirth: '2003-11-12',
    address: '45 Sussex Street, Sydney NSW 2000',
    bio: 'Interested in leadership forums, startup networking, and employability events.',
    emergencyContact: {
      name: 'Emma Johnson',
      relationship: 'Mother',
      phone: '+61 401 234 999',
    },
    interests: ['Entrepreneurship', 'Leadership', 'Networking'],
    preferences: {
      notifications: true,
      emailDigest: false,
      preferredEventCategories: ['Business', 'Careers'],
    },
  }),
  createRegisteredUser({
    id: 'user-michael-chen',
    name: 'Michael Chen',
    email: 'michael.chen@student.koi.edu.au',
    password: 'Demo@123',
    role: 'user',
    status: 'active',
    createdAt: '2026-03-06T10:10:00.000Z',
    lastLoginAt: '2026-05-03T08:05:00.000Z',
    phone: '+61 402 345 222',
    studentId: 'KOI2024003',
    course: 'Bachelor of Information Technology',
    campus: 'Sydney',
    yearLevel: 'Year 3',
    dateOfBirth: '2002-09-04',
    address: '88 George Street, Sydney NSW 2000',
    bio: 'Focuses on software engineering, AI events, and hackathon participation.',
    emergencyContact: {
      name: 'Li Chen',
      relationship: 'Father',
      phone: '+61 402 345 998',
    },
    interests: ['Software Engineering', 'Artificial Intelligence', 'Hackathons'],
    preferences: {
      notifications: true,
      emailDigest: true,
      preferredEventCategories: ['Technology', 'Workshops', 'Competitions'],
    },
  }),
  createRegisteredUser({
    id: 'user-emily-davis',
    name: 'Emily Davis',
    email: 'emily.davis@student.koi.edu.au',
    password: 'Demo@123',
    role: 'user',
    status: 'active',
    createdAt: '2026-03-07T11:00:00.000Z',
    lastLoginAt: '2026-05-02T09:10:00.000Z',
    phone: '+61 403 456 333',
    studentId: 'KOI2024004',
    course: 'Bachelor of Accounting',
    campus: 'Sydney',
    yearLevel: 'Year 1',
    dateOfBirth: '2004-01-29',
    address: '9 Clarence Street, Sydney NSW 2000',
    bio: 'Enjoys finance workshops, mentoring sessions, and academic support programs.',
    emergencyContact: {
      name: 'Olivia Davis',
      relationship: 'Mother',
      phone: '+61 403 456 997',
    },
    interests: ['Finance', 'Mentoring', 'Academic Support'],
    preferences: {
      notifications: true,
      emailDigest: false,
      preferredEventCategories: ['Academic', 'Finance'],
    },
  }),
  createRegisteredUser({
    id: 'user-robert-wilson',
    name: 'Robert Wilson',
    email: 'robert.wilson@student.koi.edu.au',
    password: 'Demo@123',
    role: 'user',
    status: 'active',
    createdAt: '2026-03-08T12:15:00.000Z',
    lastLoginAt: '2026-04-30T11:45:00.000Z',
    phone: '+61 404 567 444',
    studentId: 'KOI2024005',
    course: 'Master of Information Systems',
    campus: 'Sydney',
    yearLevel: 'Postgraduate',
    dateOfBirth: '1999-06-16',
    address: '27 Pitt Street, Sydney NSW 2000',
    bio: 'Looks for enterprise tech talks, analytics workshops, and industry panels.',
    emergencyContact: {
      name: 'Grace Wilson',
      relationship: 'Sister',
      phone: '+61 404 567 996',
    },
    interests: ['Data Analytics', 'Enterprise Systems', 'Industry Panels'],
    preferences: {
      notifications: true,
      emailDigest: true,
      preferredEventCategories: ['Technology', 'Research', 'Careers'],
    },
  }),
  createRegisteredUser({
    id: 'user-ava-patel',
    name: 'Ava Patel',
    email: 'ava.patel@student.koi.edu.au',
    password: 'Demo@123',
    role: 'user',
    status: 'active',
    createdAt: '2026-03-09T13:25:00.000Z',
    lastLoginAt: '2026-05-03T01:35:00.000Z',
    phone: '+61 405 678 555',
    studentId: 'KOI2024006',
    course: 'Bachelor of Marketing',
    campus: 'Sydney',
    yearLevel: 'Year 2',
    dateOfBirth: '2003-03-08',
    address: '54 Bathurst Street, Sydney NSW 2000',
    bio: 'Interested in branding workshops, social media strategy, and creator events.',
    emergencyContact: {
      name: 'Rina Patel',
      relationship: 'Mother',
      phone: '+61 405 678 995',
    },
    interests: ['Marketing', 'Branding', 'Content Creation'],
    preferences: {
      notifications: true,
      emailDigest: false,
      preferredEventCategories: ['Marketing', 'Creative'],
    },
  }),
  createRegisteredUser({
    id: 'user-noah-kim',
    name: 'Noah Kim',
    email: 'noah.kim@student.koi.edu.au',
    password: 'Demo@123',
    role: 'user',
    status: 'active',
    createdAt: '2026-03-10T14:05:00.000Z',
    lastLoginAt: '2026-05-01T12:55:00.000Z',
    phone: '+61 406 789 666',
    studentId: 'KOI2024007',
    course: 'Bachelor of Cyber Security',
    campus: 'Sydney',
    yearLevel: 'Year 3',
    dateOfBirth: '2002-12-21',
    address: '76 Liverpool Street, Sydney NSW 2000',
    bio: 'Follows cyber security seminars, capture-the-flag events, and research talks.',
    emergencyContact: {
      name: 'Hana Kim',
      relationship: 'Mother',
      phone: '+61 406 789 994',
    },
    interests: ['Cyber Security', 'Research', 'Competitions'],
    preferences: {
      notifications: true,
      emailDigest: true,
      preferredEventCategories: ['Security', 'Technology', 'Research'],
    },
  }),
];

module.exports = {
  registeredUsers,
};
